version: '2'
services:
  db:
    image: mysql
    env_file: .env
    ports:
      - 3306:3006
  web:
    build: .
    env_file: .env
    working_dir: /app
    ports:
      - 8000:8000
    links:
      - db:db
