# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_stripe',
            field=models.CharField(default='', max_length=50),
        ),
    ]
